demo.v

- After replacing `Axiom`s with concrete properties and proofs, I found that `RING` is the join of `AG` and `SRIG`. So I have equated `Join_AG_SRIG` and `RING`, but we need another structure in our dome to explain that we don't want to directly declare a structure which inherits more than one structure and has extra axioms.
- Declaring `type` records as primitive records seems to be generally a bad idea. So I have defined factories as we discussed before. As a result, they do work well and coercions hold the uniform inheritance condition.

Factories, renamings, and getting rid of axioms

---

demo.v

Flattened `class_of` records except in `Example1_meta`.

Flattening

---

demo2.v

- replaced generated numbers by meaningful names
- named trivial mixin factories (working around a bug?)
- sharing and factoring var-for-mixin and def-for-mixin into term-for-mixin

fix canonical_instance

---

demo2.v

Now `declare_factory` expands the target (which is possibly a factory) to a list of mixins and declares one factory for each of the possible targets using function composition. To this end we build a machinery using `mterm` to hold terms with "suspended" mixin values, a `mterm` can be turned back into a `term` by instantiating all the required mixins using `msubsts` which relies on the local db `mixin-for`.
I also abbreviated `coq.elpi.accumulate` and performed a few renamings.

Fix declare_factory

---

demo1/stage0.v
demo1/stage1.v
demo1/stage2.v
demo1/stage3.v
demo1/stage4.v
demo1/stage5.v
demo2/classical.v
demo2/stage10.v
demo2/stage11.v
demo3/stage20.v
docs/paper/demo.v
hb.elpi
hb.v
shell.nix

New syntax

---

.travis.yml

taken from https://github.com/erikmd/docker-coq-travis-ci-demo-1/blob/master/.travis.yml

ci based on docker

---

README.md
demo1/hierarchy_0.v
demo1/hierarchy_1.v
demo1/hierarchy_2.v
demo1/hierarchy_3.v
demo1/hierarchy_4.v
demo1/hierarchy_5.v
demo2/stage10.v
demo2/stage11.v
demo3/hierarchy_0.v
demo3/hierarchy_1.v
demo3/hierarchy_2.v
docs/paper/demo.v
readme.v
structures.v
tests/type_of_exported_ops.v

This looks like a final thing.
FTR, you can also use `*` instead of `&` if you prefer, and you can nest.
Currently nesting is lost, but for the display thing in order we may want to avoid flattening.

refine syntax for structures

---

.travis/docker-install.sh
.travis/docker-test.sh
FSCD2020_material/V1.v
FSCD2020_material/V2.v
FSCD2020_material/V3.v
FSCD2020_material/V4.v
README.md
_CoqProject
demo1/hierarchy_1.v
demo1/hierarchy_2.v
demo1/hierarchy_3.v
demo1/hierarchy_4.v
demo1/hierarchy_5.v
demo2/stage10.v
demo2/stage11.v
demo3/hierarchy_1.v
demo3/hierarchy_2.v
hb.elpi
structures.v

last commit may also be relevant for master when coq-elpi 1.4.0 is released

Adapt to coq/coq#12267

---

.travis.yml
coq-hierarchy-builder.opam

Waiting for https://github.com/coq/opam-coq-archive/pull/1283

coq-elpi 1.4.1

---

.github/workflows/main.yml
Changelog.md
coq-hierarchy-builder.opam
hb.elpi
structures.v

Take advantage of Coq-Elpi 1.5.x

coq-elpi 1.5

---

hb.elpi

Remove reexports of notations

---

demo1/hierarchy_0.v
demo1/hierarchy_1.v
demo1/hierarchy_2.v
demo1/hierarchy_3.v
demo1/hierarchy_4.v
demo1/hierarchy_5.v

removing spurious empty TYPE structure

---

.github/workflows/main.yml
coq-hierarchy-builder.opam

Waiting for https://github.com/coq/opam-coq-archive/pull/1480

Elpi 1.12 + Coq-Elpi 1.8.0

---

hb.elpi
structures.v

This is an extract from the branch about universe polymorphism.

cleanup structure and sub-class

---

Changelog.md

Close changelog for 1.0.0

---

.nix/config.nix
default.nix

New nix config

---

hb.elpi

Removed hack for discharging

---

Changelog.md
demo4/hierarchy_0.v
hb.elpi
structures.v
tests/display.v
tests/infer.v
tests/subtype.v

I tested it locally and it work on MC!
Fix #139
Fix #127
Fix #93

kill ty-deps, long live #[key="T"]

---

.gitignore
README.md
examples/demo1/hierarchy_5.v
examples/readme.v
hb.elpi
structures.v

Because we can... and because I'm in procrastination mode.
CC @affeldt-aist

HB.graph "file.dot".

---

HB/structure.elpi
structures.v

More readable code and doc

---

HB/builders.elpi
HB/common/phant-abbreviation.elpi
HB/context.elpi
HB/export.elpi
HB/factory.elpi
HB/instance.elpi
HB/status.elpi
HB/structure.elpi
structures.v

This is a bit massive, let's see what you think

Cleanup phant-abbreviation.elpi

---

.nix/config.nix
.nix/coq-overlays/coq-elpi/default.nix
Changelog.md
HB/common/database.elpi
HB/common/log.elpi
HB/common/utils.elpi
HB/context.elpi
HB/export.elpi
HB/instance.elpi
HB/structure.elpi
coq-hierarchy-builder.opam
structures.v
tests/exports.v

This one needs https://github.com/LPCIC/coq-elpi/pull/226 , how is the nix ci magic ? @CohenCyril 
Fix #148

#[export] HB.instance

---

HB/structure.elpi

making the class non canonical

---

HB/structure.elpi
tests/compress_coe.v.out

add a fresh int in the name of coercions

---

HB/common/database.elpi
HB/common/stdpp.elpi
HB/export.elpi
HB/instance.elpi
_CoqProject.test-suite
structures.v
tests/exports2.v

link foobar-to-export to the current file

---

HB/export.elpi
structures.v
tests/exports.v

reexport with a filter

---

HB/common/synthesis.elpi

unifying againt class constructor

---

HB/common/database.elpi
HB/common/stdpp.elpi
HB/common/synthesis.elpi
HB/instance.elpi

We use ocaml's API to speedup the access to the CS db

speedup CS db lookups

---

HB/common/utils.elpi
HB/factory.elpi
HB/structure.elpi
_CoqProject.test-suite
structures.v
tests/primitive_records.v

Here it is.
CC @nhojem @strub @pi8027

options to make some records/structures primitive

---

HB/common/utils.elpi
HB/instance.elpi
HB/structure.elpi
_CoqProject.test-suite
structures.v
tests/non_forgetful_inheritance.v

Detecting non forgetful inheritance

---

HB/instance.elpi
tests/non_forgetful_inheritance.v

@gares @chdoc happy happy happy PR

Turn NFI into a warning

---

.github/workflows/main.yml
.github/workflows/nix-action-coq-mcHB-8.16.yml
.nix/config.nix
.nix/coq-overlays/coq-elpi/default.nix
HB/common/compat_815.elpi
HB/common/compat_all.elpi
HB/common/database.elpi
HB/common/log.elpi
HB/instance.elpi
HB/structure.elpi
_CoqProject.test-suite
coq-hierarchy-builder.opam
structures.v
tests/fun_instance.v
tests/issue284.v
tests/issue287.v

Depends on #295 (because some code added there needs fixing too)
The only relevant commit is https://github.com/math-comp/hierarchy-builder/pull/296/commits/96dee3f46a8b532835840bacd11e23e591fa92bd
Fixes #287
Fixes #284

Adding missing feature: instances on function spaces

---

.github/workflows/main.yml
coq-hierarchy-builder-shim.opam
coq-hierarchy-builder.opam
tests/about.v.out.15

Update OPAM files and Docker CI accordingly

Master branch compiles on Coq 8.15

---

Changelog.md
HB/pack.elpi
_CoqProject.test-suite
tests/hb_pack.v

but we also support hierarchies of functions
CC @affeldt-aist

HB.pack was asserting the key is a type

---

examples/hulk.v

workaround https://github.com/coq/coq/issues/17223

Avoid memory increase in hulk.vo

---

Changelog.md
coq-hierarchy-builder.opam

close changelog & update opam

---

tests/funclass.v

Adapt ro https://github.com/coq/coq/pull/18164

Adapt ro https://github.com/coq/coq/pull/18164

---

_CoqProject.test-suite
tests/factory_when_notation.v

EDIT: 2023-11-30
Does not fail anymore, adding to test-suite.
Related to #220

Testsuite item for #220

---

HB/common/utils.elpi

make copy-pack-holes failsafe

---

HB/common/stdpp.elpi

fix mode signature

---

Makefile.test-suite.coq.local

Adapt to https://github.com/coq/coq/pull/20028

Adapt to https://github.com/coq/coq/pull/20028

---

HB/common/utils.elpi

Adapt to https://github.com/LPCIC/coq-elpi/pull/750

Adapt to https://github.com/LPCIC/coq-elpi/pull/750

---

.github/workflows/nix-action-coq-8.20.yml
.github/workflows/nix-action-coq-9.0.yml
.github/workflows/nix-action-coq-master.yml
.nix/config.nix
.nix/coq-overlays/coqeal/default.nix

Now that it compiles on Coq >= 9 thanks to the replacement of paramcoq by elpi derive.param2.

[CI] Readd coqeal

---

rocq-hierarchy-builder.opam

changed dependency, from coq-elpi to rocq-elpi

---

Makefile
coq-hierarchy-builder.opam

Was no longer working on Rocq without coq shim

Fix makefile
