demo2.v
Toposort may not work properly to sort vertices `{x, z}` of the graph `x -> y -> z` (`y` cannot be found in the set of vertices to sort) if we use the remaining vertices instead of `ES` in L.92. So I think this is the only possible fix.
=> Fix toposort

demo2.v
This PR adds support for generating a `phant_id` / `unify` (see *Canonical Structures for the working Coq user* by Mahboubi & Tassi) based notation for mixin and factory types.
A minor extension is needed to generate `pack` and `clone` from this.
=> Generating abbrevations *à la* `pack` for mixin and factory types

demo2.v
- `declare_mixin` is renamed `mixin_requires` and take an explicit list of dependencies, `declare_mixin` is now free to be used in the way suggested in a comment, consequently 
+ `export-1-operation` and `synthesize-fields` were broken and rewritten with `msubst` (which is a more robust way to instantiate mixins and propagate `mixin-src`),
+ `mixin-deps` is completely subsumed by `factory-requires`, and hence removed,
- `msubst` is renamed `instanciate-mixin`
- `msubsts` is renamed `mterm->term`
- `mgref->term T GR X` automatically computes the maximal dependency list for `GR` and then is chained `mterm->term` to get a term without mixin abstractions at all,
- `mixin->mterm` was always combined with `mterm->term`, so its use is replaced by `mgref->term`,
- `factory->mterm` was always …
=> Introducting `mixin_requires` + renamings and refactorings

demo2.v
- The remaining commands are:
+ `hb.declare` and `hb.end` to declare new mixins and factories,
(actually, only `hb.end` is doing smart stuff and lets the user decide whether this goes to `factory` or `mixin`, `hb.declare` is simply opening a module, a section and calls `hb.context`)
+ `hb.context` to extend a context on demand inbetween `hb.declare` and `hb.end`,
+ `hb.structure` to make a new structure out of factories,
+ `hb.canonical` to make new canonical structures.
- Hence, removing `factory_requires`, `declare_factory_fun` and `mixin_requires` in favor of `hb.declare` and `hb.end`
- Also shortening export-operation implem
- Exporting not only ops from axioms but also theorems
- `hb.canonical` does not populate/pollute the local persistent mixin-src anymore, and tries to reconstruct …
=> Simplifying the Language

hb.elpi, hb.v
I think current master is broken: elpi 1.9 does not like macros in types (since there is a typeabbrev directive) and coq-elpi master has now a ternary coq.typecheck
If this works and if LPCIC/coq-elpi#103 is OK then I plan to release a new version of coq-elpi
=> use typeabbrev for types and assert-ok! for typecheck

demo1/stage0.v, demo1/stage1.v, demo1/stage2.v, demo1/stage3.v, demo1/stage4.v, demo1/stage5.v, demo2/stage10.v, demo2/stage11.v, hb.elpi, hb.v
- factory declaration are now gathered from instances
- when we have an Axiom_ A constructor, no need to put the axiom_ A type
- Qc is a toplogical group, and is "automatically" uniform
- fixed a bug in instanciate-mixin
=> shortenings + new instance Qc + bugfixes

docs/paper/hb.tex
I suggest changing mathematical notations like `\requires` and `\provides` to fix spacing as in this PR.
=> Fix math notations

README.md, demo1/hierarchy_0.v, demo1/hierarchy_1.v, demo1/hierarchy_2.v, demo1/hierarchy_3.v, demo1/hierarchy_4.v, demo1/hierarchy_5.v, demo1/user_0.v, demo1/user_3.v, demo2/stage10.v, demo2/stage11.v, demo3/hierarchy_0.v, demo3/hierarchy_1.v, demo3/hierarchy_2.v, demo3/user_0.v, hb.elpi, readme.v, structures.v, tests/duplicate_structure.v, tests/type_of_exported_ops.v
Two things to do:
- demo2 has an error since `TAddAG` is also a definition (before it becomes a structure). @CohenCyril I let you decide what to do
- ~We need to replace all `F.axioms` by `F` in the files~
Question:
- now `Foo` is the type of the factory, while `Foo.Axioms` is the constructor. Maybe we should rename/alias it to something nicer? `Foo.Build` maybe? The last commit implements it, it is easy to drop
=> Generate an abbreviation `F X` for `F.axioms X` (fix #61)

demo1/hierarchy_1.v, demo1/hierarchy_2.v, demo1/hierarchy_3.v, demo1/hierarchy_4.v, demo1/hierarchy_5.v, demo2/stage10.v, demo2/stage11.v, demo3/hierarchy_1.v, demo3/hierarchy_2.v, hb.elpi, structures.v
- former axioms can be recovered by prefixing with the module name,
- former theorems *cannot*, which causes major breakage when the library evolves.
=> Factory fields now mask lemmas and operators by default

.travis/docker-install.sh, .travis/docker-test.sh, _CoqProject, demo4/hierarchy_0.v, hb.elpi, structures.v
```coq
HB.mixin Record (P1 : T1) ... (A : Type) foo of f1 P1 A & .. & f2 P1 (P1 * P2) A := {
...
}.
```
The key is to represent the dispatching a factory does of its parameters to the underlying mixins.
Here for example here `foo P1 ..` passes `P1` to `f1` and `P1`, `P1 * P2` to `f2`.
A dispatching is an arbitrary function from parameters to a list of parameters.
The code base has a new data type `list-w-params A` and `w-params A` to represent it.
Fix #75
=> [feature] parameters in structures

hb.elpi
E.g. in `Definition t a b := K (T a b) (C a b).` if you unify `t x y = _ _ c` you don't necessarily force the unfolding of `t` and `c` could get `y`, while with `t x y = K _ c` you do, since the RHS is a rigid HNF hence the LHS must be reduces to expose `K` and `c` gets `C x y`
=> In `HB.instance` force unification to extract the class instead of the second argument.

structures.v
This seems like a big bug even if I don't undestand yet how it was working.
If you don't typecheck the type first, and pass it as the expected type of coq.typecheck, you get a unification problem like this one:
```
(monoid_of_semigroup.axioms_ M is_monoid_semigroup)   =?1=   
(monoid_of_semigroup.phant_axioms M ?e24 ?e26 (@id_phant ?e28 ?e30) 
?e32 (@id_phant ?e34 ?e36) ?e38 (@id_phant ?e40 ?e42)
(@id_phant ?e44 ?e46))
```
Coq is able to solve it (in 8.11) without assigning the arguments of id_phant (only ?e24/26 IIRC). In 8.12 as well, but later on the system "realizes that".
I'm hesitating, coq.typecheck could typecheck the expect type if given before unifying it with the inferred one...
This fix makes sense anyway.
=> [instance] typecheck the type first

hb.elpi
=> Better error message in case of wrong structure definition order

Changelog.md, hb.elpi
- A non-obvious fix for an obvious bug
- Update changelog
=> Fix the join of structures with parameters + changelog

Changelog.md, coq-hierarchy-builder.opam, demo2/stage10.v, demo2/stage11.v, hb.elpi, structures.v
That's it.
~~It requires a non released version of Coq-Elpi (including PR LPCIC/coq-elpi#170). It would be nice if it we could give it a try on mathcomp before releasing Coq-Elpi 1.6 (so that we are sure we don't miss something in LPCIC/coq-elpi#170).~~
~~Depends on LPCIC/coq-elpi#170 it was tested locally and works, here CI does not pick up the needed Coq-Elpi branch.~~
Fix #98 #34
=> use Coq's elaborator for factories and instances

hb.elpi, structures.v, tests/subtype.v
We now run type inference *but* we first turn all `id_phant` into `_`. The problem is that if you don't do that the term does not type check, e.g. the factory requires are not postulated (yet). Similarly in structures, before we were ignoring (no type inference for the parameters) parameters and then we were postulating all requires.
IMO this PR makes things a bit more predictable (and similar to the usual way Coq works), but this is a sharp weapon since inference goes left to right, so you should put the most demanding factory (on parameters) first (in a structure declaration).
There is also another subtle problem with `indexed` that stays there in some terms and type inference can put it in the type of a parameter breaking things (see the commit in the test suite).
Fix #134
Fix #133
=> Elaboration of parameters in HB.structure and HB.builders

hb.elpi
- factory local definitions were not taking parameters into account.
- making sure factory/mixin arguments are always explicit.
=> Bugfix: forgotten parameters

.github/workflows/main.yml, _CoqProject, hb.elpi, structures.v, tests/infer.v
The syntax is `#[infer(P = "something")]` and `#[infer(P)]` is also supported and works as `P = "Type"`.
Fix #140
=> inference of structures on paramters

structures.v
the first one brings down the last instance in ssralg to 0.4s, slow but tolerable.
the second one is just to avoid being silly and store `s.phant_Build crap` instead of `s.Build less crap`, it does not impact performances too much for not.
I believe the root problem is still there:
```
Set Printing All. Print prod_is_a_Ring.
(*
prod_is_a_Ring = 
@Ring.Pack (prod (Ring.sort R1) (Ring.sort R2))
(@Ring.Class (prod (Ring.sort R1) (Ring.sort R2))
(HB_unnamed_factory_105 (Ring_to_Zmodule R1) (Ring_to_Zmodule R2))
(prod_eqMixin
(Choice_to_Equality (Zmodule_to_Choice (Ring_to_Zmodule R1)))
(Choice_to_Equality (Zmodule_to_Choice (Ring_to_Zmodule R2))))
(prod_choiceMixin (Zmodule_to_Choice (Ring_to_Zmodule R1))
(Zmodule_to_Choice (Ring_to_Zmodule R2))) HB_unnamed_factory_107)
: Ring.type
*)
``` …
=> optimizations

.nix/config.nix, .nix/coq-overlays/mathcomp-single/default.nix, hb.elpi, structures.v
- "arg_sort" adds an intermediate coercion class `arg_sort` as
documented in the header of fingroup.v
cf https://github.com/math-comp/math-comp/tree/hierarchy-builder-fingroup/mathcomp
- test against hierarchy-builder math-comp branch
=> Attribute "arg_sort"

HB/common/database.elpi
Locally this saves 15s in compiling ssralg, together with https://github.com/LPCIC/coq-elpi/pull/220 I'm down to 30s (from 60s).
The code sucks, but I want to see what nix CI says.
CC @pi8027 @CohenCyril
=> speedup toposort mixins

.github/workflows/nix.yml, Changelog.md, HB/common/database.elpi, HB/common/stdpp.elpi, HB/common/synthesis.elpi, HB/common/utils.elpi, HB/instance.elpi, HB/structure.elpi, Makefile.test-suite.coq.local, _CoqProject.test-suite, structures.v, tests/compress_coe.v, tests/compress_coe.v.out
Hi @gares here is a fix for having shorter coercion paths in https://github.com/math-comp/hierarchy-builder/issues/150.
Unfortunately in the current state, it makes everything even slower, probably because I did not find the right API functions to get as specific coercion, or because it is not bound yet... you tell me
Fix #150
=> Shortening coercions in mixins.

HB/common/log.compat.current.elpi, HB/common/log.elpi, HB/common/utils.elpi, HB/instance.elpi, _CoqProject.test-suite, structures.v, tests/local_instance.v
This pr:
- adds `#[local]` to `HB.instance`
- document which command supports which attribute. If you pass a non-supported attribute to a command you get an error.
- fixes #88
=> HB.instance understands #[local]

HB/builders.elpi, HB/common/database.elpi, HB/common/log.elpi, HB/common/stdpp.elpi, HB/common/utils.elpi, HB/context.elpi, HB/export.elpi, HB/graph.elpi, HB/instance.elpi, HB/structure.elpi, structures.v, tests/compress_coe.v, tests/compress_coe.v.out, tests/exports.v
The primitive is `gref->modname` which now takes a number of components and a separator.
In this way we can take 2 pieces, eg `GRing_Zmodule`.
Also, add-const ensure fresheness in case of collision, so names are way less borked.
Hb.graph is now working ok.
The decision of taking 2 components is arbitrary, works for MC.
=> cleanup the name collision mess

HB/common/log.elpi, HB/factory.elpi, HB/instance.elpi, HB/structure.elpi, README.md, structures.v, tests/about.v, tests/about.v.out
We move all code storing locations in the logging module, and we export HB.locate to know where stuff synthesized by HB is located
=> Cleanup about locations + HB.locate

.nix/coq-overlays/coq-elpi/default.nix, HB/common/log.current.elpi, HB/common/log.elpi, HB/instance.elpi, coq-hierarchy-builder.opam
from
```
real	12m36,750s
user	31m43,786s
sys	0m22,771s
```
to
```
real	11m57,060s
user	28m7,674s
sys	0m22,622s
```
Depends on https://github.com/LPCIC/coq-elpi/pull/237
=> make direct mixins opaque

HB/common/phant-abbreviation.elpi, examples/Coq2020_material/CoqWS_expansion/withoutHB.v, structures.v
```Coq
Print Universes Subgraph (unify.u2 option.u0 prod.u1).
```
gave
```
unify.u2 < option.u0
< prod.u1
```
and those constraint then dripped on every structures.
This became an issue when porting CoqEAL refinements.
We thus use a specific sum type instead of option and prod.
=> Remove universe constraint between unify, option and prod

tests/compress_coe.v.out
Hi, Coq's PR coq/coq#14596 grants wish coq/coq#13830 and let `Arguments` display all names in `About`/`Print`. This PR adapts the hierarchy builder tests so that it continues to be consistent with Coq's CI.
To be merged synchronously with coq/coq#14596.
=> Adapt to coq PR #14596 which let Arguments displaying all names in About/Print

Changelog.md
=> close Changelog.md before release

HB/common/phant-abbreviation.elpi, HB/common/synthesis.elpi, _CoqProject.test-suite, tests/grefclass.v
I need this when porting all the closedness predicates in ssralg.v in mathcomp, in order to have their sort of type `{pred _}` rather than `_ -> bool` and write `_ \in S` rather than `_ \in (S : pred _)` everywhere.
=> Support grefclass

HB/common/synthesis.elpi, HB/structure.elpi, structures.v, tests/compress_coe.v.out, tests/hnf.v.out, tests/infer.v
Elpi's compiler is slow/naive when it comes to grafting clauses.
This PR rephrases the `compress` predicate so that we don't need to insert clauses `:before` the anchor point.
On my laptop on 8.17 we go from
```
real	34m47,869s
user	34m23,509s
sys	0m23,660s
```
to
```
real	26m54,973s
user	26m32,587s
sys	0m22,236s
```
=> Speedup `compress` clause insertion

Makefile.test-suite.coq.local
Hopefully makes the log more readable considering wdiff prints the whole .out.
=> Print FAILED foo.v when a test fails

HB/common/log.elpi
https://github.com/coq/coq/pull/17484 broke mathcomp. I should do some profiling to check this but there is no obvious dramatic effect.
=> Fixing mathcomp after coq/coq#17484

HB/common/log.elpi
No longer necessary since https://github.com/coq/coq/pull/17853
=> Revert "Fixing mathcomp after coq/coq#17484"

HB/about.elpi, HB/common/compat_acc_clauses_816.elpi, HB/common/compat_acc_clauses_all.elpi, HB/common/database.elpi, HB/common/log.elpi, HB/common/synthesis.elpi, HB/common/utils.elpi, HB/context.elpi, HB/structure.elpi, structures.v, tests/about.v.out, tests/about.v.out.15, tests/hnf.v, tests/hnf.v.out, tests/hnf.v.out.15, tests/hnf.v.out.16
Compilation of MathComp:
* before: 22:57 (1.53 GB)
* HB.structure: 05:42
* HB.instance: 02:31
* HB.mixin: 00:19
* HB.factory: 00:32
* HB.builders: 00:23
* HB.pack(_for): 00:15                                                                                           
* after: 17.22 (1.27 GB)                                                                                           
* HB.structure: 01:38                                                                                            
* HB.instance: 02:21                                                                                             
* HB.mixin: 00:18                                                                                                
* HB.factory: 00:32 …
=> A few performance improvements

Changelog.md, HB/common/utils.elpi, HB/structure.elpi, structures.v, tests/fix_loop.v, tests/primitive_records.v
Compilation of MathComp:
* before: 16:34 (1.37 GB)
* after: 14:20 (1.37 GB)
* mathcomp1: 06:16 (0.97 GB) (time x 2.29 (memory x 1.31))
Compilation of Analysis:
* before: 20:59 (1.81 GB)
* after: 12:30 (1.76 GB)
* analysis master: 07:49 (1.55 GB) with HB 1.4 (time x 1.60 (memory x 1.14))
or 06:32 (1.25 GB) with HB 1.6 (time x 1.91 (memory x 1.41))
=> Make primitive_class the default

tests/missing_join_error.v.out
propagate a typo fix to `tests`
attempts to address https://github.com/math-comp/hierarchy-builder/pull/425#issuecomment-2174959330
=> typo addd in tests

HB/howto.elpi, tests/howto.v.out
At CUDW 2024, we discussed the idea of ​​writing a guide for declaring mathcomp instances. 
This PR refers to that guide.
=> at the end of HB.howto output, it suggests a link to a guide on how to declare mathcomp instances 

HB/common/database.elpi, structures.v
since we accumulate clauses about it in HB.structure
It should be backward compatible and unblock https://github.com/LPCIC/elpi/pull/264 (that makes the startup time of elpi programs much smaller, but requires types to be declared before the clauses)
=> put factory-alias->gref in the database

HB/common/synthesis.elpi, Makefile.test-suite.coq.local, tests/err_miss_dep.v, tests/err_miss_dep.v.out
=> improve error message missing mixin dep

HB/factory.elpi, Makefile.test-suite.coq.local, tests/err_miss_key.v, tests/err_miss_key.v.out
=> detect bogus #[key] attribute

HB/common/synthesis.elpi
Fix regression in 1.7.1 affecting Monae
Fix #477
=> Funclass can be dependent

HB/instance.elpi, Makefile.test-suite.coq.local, tests/err_bad_mix.v, tests/err_bad_mix.v.out
=> improve error message on instance of not a factory

HB/instance.elpi, _CoqProject.test-suite, tests/bug_435.v, tests/bug_447.v
It may be due to a parameter being not rich enough for a mixin we were able to found during synthesis.
Fixes #435
Fixes #447
=> HB.instance: failure building a class is not fatal

HB/instance.elpi, HB/structures.v, Makefile.test-suite.coq.local, tests/about.v.out, tests/compress_coe.v.out, tests/err_instance_nop.v, tests/err_instance_nop.v.out, tests/err_miss_dep.v.out, tests/howto.v.out, tests/missing_join_error.v.out
=> warning if HB.instance does nothing

HB/common/utils.elpi
This reverts commit 82ee41024b535bdefff405a11188a88c729e267e that appears finally not needed.
=> Revert "Adapt to https://github.com/LPCIC/coq-elpi/pull/750"

Makefile
The `sed` command in the makefile fails for MacOS. This MR changes it to a version compatible with more OSes.
=> Modify `sed` command in the makefile

HB/common/utils.elpi
HB.about is unusable on any MC structure since https://github.com/math-comp/hierarchy-builder/pull/527
Fixes: https://github.com/math-comp/hierarchy-builder/issues/552
=> Fix HB.about
